### PR TITLE
Add TransportDecorator to the parameter set

### PR DESCRIPTION
**Pull request by paulmey**
Allows addition of logic to (or complete replacement of) the http stack

### CODE REVIEW

**Comment by paulmey** [comment]
Enables #6 by hooking up github.com/paulmey/ntlmssp like this:
``` Go
params := winrm.DefaultParameters()
params.TransportDecorator = func(t *http.Transport) http.RoundTripper { return ntlmssp.Negotiator{t} }
c, err := winrm.NewClientWithParameters(..., params)
```

**Comment by masterzen** [comment]
LGTM. 
Can you, please, add your example to the README so that people know how to use this feature?

**Comment by paulmey** [comment]
How about this?

**Comment by masterzen** [comment]
Thanks @paulmey, this looks good!

**Pull request merged**
