### PR TITLE
Fix #49 split the library and the command-line tool

### LINKED ISSUE #49: Separating the cli executable from the library.
@masterzen think it's a good time to make this proposal
I propose to decouple the executable code from the api code. It's starts to be ugly and we should use a library-framework to easily customize and develop our binary-executable-tool.
This way it's more easily to make changes to the API without adding/deleting things on executable and vice-versa. Plus a better error handling system in the code overal. What do you think?

We could easily use this wonderful libraries for command line apps.
https://github.com/spf13/cobra
https://github.com/codegangsta/cli
https://github.com/hoenirvili/Skapt
https://github.com/alecthomas/kingpin

### PR DESCRIPTION
**Pull request by masterzen**
This is a breaking change. The tool has been moved to the winrm-cli
project (https://github.com/masterzen/winrm-cli).
This commit removes the tool, and moves back all the library code
to the github.com/masterzen/winrm package.

Dependent libraries or tool might need to be modified to take the new
package path into account.

### CODE REVIEW

**Comment by masterzen** [comment]
I'd like to gather inputs from the Packer WinRM Communicator community (@mefellows @boumenot @dylanmei @sneal and possibly others). Feel free to comment in this PR. 

This will require to update the winrm communicator and winrmcp to point to the new (simpler) library package (`github.com/masterzen/winrm` instead of `github.com/masterzen/winrm/winrm`).

**Comment by hoenirvili** [comment]
Why removing x509 cert generation support from the api?

**Comment by masterzen** [comment]
@hoenirvili because this was used only by the `winrm` executable (and as I already stated this isn't really something that is required for running the library). So I moved this feature to the [winrm-cli](https://github.com/masterzen/winrm-cli).

**Comment by hoenirvili** [comment]
So what about the winrm.go/ code that was left there?

**Comment by hoenirvili** [comment]
So you are planning to move all the code form winrm/ folder into the masterzen/winrm/ root ?

**Comment by masterzen** [comment]
@hoenirvili yes, I never liked the `winrm/winrm` package, and it seems most Go library are directly defined at the root, so why not do that?
It's cumbersome for the dependent projects, that's why I'm trying to gather comments from the Packer community (and any other projects dependent of this library).

**Comment by sneal** [comment]
:+1: Nice, I like the simplified package path for the core library.

**Comment by mefellows** [comment]
I'm all for it @masterzen. I can make a fix to Packer tonight if it's not already done.

**Comment by masterzen** [comment]
Let's merge it then.

**Comment by dylanmei** [comment]
I've updated `packer-community/winrmcp`.

**Pull request merged**
