### PR TITLE
RunPSWithString function added

### PR DESCRIPTION
**Pull request by mertcelen**
It allows to be able to send commands directly to powershell rather than cmd

### CODE REVIEW

**Comment by masterzen** [comment]
Hi,
This looks good, and would fix the stale PR #97 which I wasn't really fond of.

But, we already have a `Powershell` function that generates the powershell command to be used with `RunWithString`. We could remove the `Powershell` function, but that would break the API.
Instead, would you mind rewriting your PR so that `RunPSWithString` internally calls `Powershell`, and move the gory details (like the UTF16 conversion) to that function ?

Thanks !

**Comment by mertcelen** [comment]
I've applied changes :)

**Comment by mertcelen** [comment]
@masterzen do you need anything else?

**Comment by masterzen** [comment]
@mertcelen thanks for the reminder, I totally forgot your PR.
It looks good to me, many thanks for your contribution !

**Pull request merged**
