### PR TITLE
remove dependency for github.com/masterzen/azure-sdk-for-go

### PR DESCRIPTION
**Pull request by rmb938**

### CODE REVIEW

**Comment by masterzen** [comment]
@rmb938 thanks for your contribution !

I will do a few tests ASAP, and let you know the results.

I think we should also modify the `README.md` file to indicate that this library only supports go 1.7+, and also modify `travis.yml` to remove the old Go versions (I can do it in a subsequent commit if you want).

**Comment by taliesins** [comment]
I pulled the latest version of WinRM in and applied this change. The problem I ran into is it seems xmlTree now needs a non strict default to be passed in.

```
func TestXmlParsePass(t *testing.T){
	response := `<s:Envelope xml:lang="en-US" xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:x="http://schemas.xmlsoap.org/ws/2004/09/transfer" xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" xmlns:rsp="http://schemas.microsoft.com/wbem/wsman/1/windows/shell" xmlns:p="http://schemas.microsoft.com/wbem/wsman/1/wsman.xsd"><s:Header><a:Action>http://schemas.xmlsoap.org/ws/2004/09/transfer/CreateResponse</a:Action><a:MessageID>uuid:745C68FA-F8BD-4625-92DC-751031BCA342</a:MessageID><a:To>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:To><a:RelatesTo>uuid:e07599dd-c8f8-465f-51a7-7aac944dd768</a:RelatesTo></s:Header><s:Body><x:ResourceCreated><a:Address>http://127.0.0.1:5985/wsman</a:Address><a:ReferenceParameters><w:ResourceURI>http://schemas.microsoft.com/wbem/wsman/1/windows/shell/cmd</w:ResourceURI><w:SelectorSet><w:Selector Name="ShellId">396A9E30-C79E-4062-A337-627009263DB7</w:Selector></w:SelectorSet></a:ReferenceParameters></x:ResourceCreated><rsp:Shell xmlns:rsp="http://schemas.microsoft.com/wbem/wsman/1/windows/shell"><rsp:ShellId>396A9E30-C79E-4062-A337-627009263DB7</rsp:ShellId><rsp:ResourceUri>http://schemas.microsoft.com/wbem/wsman/1/windows/shell/cmd</rsp:ResourceUri><rsp:Owner>Administrator</rsp:Owner><rsp:ClientIP>127.0.0.1</rsp:ClientIP><rsp:IdleTimeOut>PT7200.000S</rsp:IdleTimeOut><rsp:InputStreams>stdin</rsp:InputStreams><rsp:OutputStreams>stdout stderr</rsp:OutputStreams><rsp:ShellRunTime>P0DT0H0M0S</rsp:ShellRunTime><rsp:ShellInactivity>P0DT0H0M0S</rsp:ShellInactivity></rsp:Shell></s:Body></s:Envelope>`

	xmlSettings := func(s *xmltree.ParseOptions){
		s.Strict = false
	}

	_, err := xmltree.ParseXML(strings.NewReader(response), xmlSettings )
	if err != nil {
		panic( fmt.Errorf("unable to parse xml response: %v, %v", response, err))
	}
}

func TestXmlParseFail(t *testing.T){
	response := `<s:Envelope xml:lang="en-US" xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:x="http://schemas.xmlsoap.org/ws/2004/09/transfer" xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" xmlns:rsp="http://schemas.microsoft.com/wbem/wsman/1/windows/shell" xmlns:p="http://schemas.microsoft.com/wbem/wsman/1/wsman.xsd"><s:Header><a:Action>http://schemas.xmlsoap.org/ws/2004/09/transfer/CreateResponse</a:Action><a:MessageID>uuid:745C68FA-F8BD-4625-92DC-751031BCA342</a:MessageID><a:To>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:To><a:RelatesTo>uuid:e07599dd-c8f8-465f-51a7-7aac944dd768</a:RelatesTo></s:Header><s:Body><x:ResourceCreated><a:Address>http://127.0.0.1:5985/wsman</a:Address><a:ReferenceParameters><w:ResourceURI>http://schemas.microsoft.com/wbem/wsman/1/windows/shell/cmd</w:ResourceURI><w:SelectorSet><w:Selector Name="ShellId">396A9E30-C79E-4062-A337-627009263DB7</w:Selector></w:SelectorSet></a:ReferenceParameters></x:ResourceCreated><rsp:Shell xmlns:rsp="http://schemas.microsoft.com/wbem/wsman/1/windows/shell"><rsp:ShellId>396A9E30-C79E-4062-A337-627009263DB7</rsp:ShellId><rsp:ResourceUri>http://schemas.microsoft.com/wbem/wsman/1/windows/shell/cmd</rsp:ResourceUri><rsp:Owner>Administrator</rsp:Owner><rsp:ClientIP>127.0.0.1</rsp:ClientIP><rsp:IdleTimeOut>PT7200.000S</rsp:IdleTimeOut><rsp:InputStreams>stdin</rsp:InputStreams><rsp:OutputStreams>stdout stderr</rsp:OutputStreams><rsp:ShellRunTime>P0DT0H0M0S</rsp:ShellRunTime><rsp:ShellInactivity>P0DT0H0M0S</rsp:ShellInactivity></rsp:Shell></s:Body></s:Envelope>`

	_, err := xmltree.ParseXML(strings.NewReader(response))
	if err != nil {
		panic( fmt.Errorf("unable to parse xml response: %v, %v", response, err))
	}
}
```

**Comment by azr** [comment]
Hello here, is this PR missing something then ?

**Comment by rmb938** [comment]
@masterzen Could we look into getting this merged?

**Comment by masterzen** [comment]
I'm very sorry for the lack of actions on this PR.
This looks correct, and I'm going to merge it :)

Thanks!

**Pull request merged**
