### PR TITLE
Fix race condition between command.Wait() and fetchOutput

### PR DESCRIPTION
**Pull request by paulmey**
I've observed the exitcode sometimes coming back as 0 if it should have been non-zero. 
It turns out that both command.Wait() and fetchOutput(* command) were racing to receive command.done. The break statements were only [breaking out of the select, not the for loop](https://golang.org/ref/spec#Break_statements), so the exit code kept being updated forever. 

Apparently at least one implementation of WSMAN returns ExitCode 0 on subsequent Receive messages, even though it was non-zero on the first Receive response with `CommandState/@State=done`.

I changed fetchOutput/Wait to the canonical 'done channel' pattern to terminate on the first encounter of a `CommandState/@State=done` fragment.

Not sure why fetchOutput was trying to receive command.done, since it's only sent by the very same function?

### CODE REVIEW

**Comment by masterzen** [comment]
We used to signal the `command.done` channel from command `Close`, but it somehow disappeared. So either it wasn't necessary, as the slurp will terminate if we close to the server, or it's a bug and we can't close a running command.

**Comment by paulmey** [comment]
In the current code, fetchOutput never terminates, I believe. The break's only break out of the select clause, not the for loop. Even in this case, a command could get stuck, if the server never returns 'done' (ie. it's waiting for input in pending state).

**Comment by masterzen** [comment]
That's right, the code was broken. I'm just trying to figure out if we need to restore the original behavior (ie allowing to exit `fetchOutput`) if we `Close`, or if the server will return `done` anyway...

**Comment by paulmey** [comment]
IMHO, closing/cancelling a command should be a separate channel, like [this](https://github.com/paulmey/winrm/commit/db375ac79c34a35685ddba2b0e082b1e64264f95). If that's what you want, I can add that to this PR. Seems like a good idea to me to not trust the server to do the right thing? Or we could give it a timeout (i.e. close the channel in a go routine which first waits for a certain time)?

**Comment by masterzen** [comment]
@paulmey this looks good to me. Can you add the `cancel` feature to this PR (in a separate commit maybe)?
I'm not sure about the timeout though, I fear it would add complexity all over this part of the code (and add more complexity for the clients of this code).

**Comment by paulmey** [comment]
Done. TALP...

**Comment by masterzen** [comment]
@paulmey, do you think you could add a test for the second patch?

**Comment by paulmey** [comment]
Yep I'll work on that. I'm a bit busy with some other things, so it might take a couple of days... not sure. :-)

**Comment by paulmey** [comment]
Added tests to master, verified they detect the bugs, rebased fixes on top to verify that the bugs are now fixed.

**Comment by masterzen** [comment]
Thanks @paulmey , this looks good! Merging...

**Pull request merged**
